language: python
python:
    - 3.8.3
services:
    - docker
before_script:
    - pip install docker-compose
    - docker-compose build
    - docker-compose up
script:
    - docker-compose run web python manage.py test question
