language: python
python:
    - 3.8.3
services:
    - docker
before_script:
    - pip install docker-compose
    - docker-compose build
    - docker-compose up -d
script:
    - sleep 20
    - docker-compose exec web python manage.py test question
